In [1]:
l = list('abc')

In [2]:
l

['a', 'b', 'c']

In [95]:
inputfile = './原书代码数据/chapter8/test/data/apriori.txt'
f = open(inputfile,'r',encoding='utf-8')
data = pd.read_csv(f,sep=',',header=None)
f.close()
data.head()

data.values



array([['A2', 'B1', 'C3', ..., 'E1', 'F1', 'H1'],
       ['A2', 'B1', 'C3', ..., 'E1', 'F1', 'H1'],
       ['A2', 'B1', 'C3', ..., 'E1', 'F1', 'H1'],
       ..., 
       ['A4', 'B3', 'C4', ..., 'E1', 'F4', 'H2'],
       ['A4', 'B3', 'C4', ..., 'E1', 'F4', 'H2'],
       ['A4', 'B3', 'C4', ..., 'E1', 'F4', 'H2']], dtype=object)

In [12]:
ct = lambda x : Series(1,index=x)

b = map(ct,data.values)
k = DataFrame(list(b))

k.fillna(0).applymap(lambda x : '{:0.0f}'.format(x))



A2 B1 C3 D3 E1 F1 H1 B2 A1 C1 ... B4 E4 H4 D4 A4 B3 F2 C4 F3 F4
0    1  1  1  1  1  1  1  0  0  0 ...  0  0  0  0  0  0  0  0  0  0
1    1  1  1  1  1  1  1  0  0  0 ...  0  0  0  0  0  0  0  0  0  0
2    1  1  1  1  1  1  1  0  0  0 ...  0  0  0  0  0  0  0  0  0  0
3    1  1  1  1  1  1  1  0  0  0 ...  0  0  0  0  0  0  0  0  0  0
4    1  0  1  1  1  1  1  1  0  0 ...  0  0  0  0  0  0  0  0  0  0
5    0  0  0  0  1  1  1  1  1  1 ...  0  0  0  0  0  0  0  0  0  0
6    0  1  0  0  1  1  1  0  1  1 ...  0  0  0  0  0  0  0  0  0  0
7    0  0  0  0  1  1  1  1  1  1 ...  0  0  0  0  0  0  0  0  0  0
8    0  0  0  0  1  1  1  1  1  1 ...  0  0  0  0  0  0  0  0  0  0
9    0  0  0  0  1  1  1  1  1  1 ...  0  0  0  0  0  0  0  0  0  0
10   0  0  0  1  0  1  0  1  1  1 ...  0  0  0  0  0  0  0  0  0  0
11   0  0  0  0  0  1  0  1  0  1 ...  0  0  0  0  0  0  0  0  0  0
12   1  0  0  1  1  1  0  1  0  1 ...  0  0  0  0  0  0  0  0  0  0
13   1  0  0  1  1  1  0  1  0  1 ...  0  0  0  0  0  0  0  0  0  0
14   1  1  1  0  1  1  0  0  0  0 ...  0  0  0  0  0  0  0  0  0  0
15   0  1  0  0  0  1  1  0  1  0 ...  0  0  0  0  0  0  0  0  0  0
16   1  0  0  1  1  1  0  1  0  1 ...  0  0  0  0  0  0  0  0  0  0
17   0  0  0  1  0  1  0  1  1  1 ...  0  0  0  0  0  0  0  0  0  0
18   0  0  0  1  0  1  0  1  1  1 ...  0  0  0  0  0  0  0  0  0  0
19   0  0  0  1  0  1  0  1  1  1 ...  0  0  0  0  0  0  0  0  0  0
20   0  0  0  0  0  1  0  1  0  1 ...  0  0  0  0  0  0  0  0  0  0
21   0  1  0  0  1  1  1  0  0  0 ...  0  0  0  0  0  0  0  0  0  0
22   0  0  0  0  0  1  0  1  0  1 ...  0  0  0  0  0  0  0  0  0  0
23   0  0  0  1  0  1  0  1  1  1 ...  0  0  0  0  0  0  0  0  0  0
24   1  0  0  0  0  1  0  1  0  1 ...  0  0  0  0  0  0  0  0  0  0
25   0  0  0  1  0  1  0  0  0  0 ...  1  1  1  0  0  0  0  0  0  0
26   0  1  0  0  1  1  1  0  0  0 ...  0  0  0  0  0  0  0  0  0  0
27   0  0  0  0  0  1  0  1  1  1 ...  0  0  0  0  0  0  0  0  0  0
28   0  1  0  0  1  1  1  0  0  0 ...  0  0  0  0  0  0  0  0  0  0
29   0  1  0  0  0  1  1  0  1  0 ...  0  0  0  0  0  0  0  0  0  0
..  .. .. .. .. .. .. .. .. .. .. ... .. .. .. .. .. .. .. .. .. ..
900  1  0  0  0  0  0  0  0  0  1 ...  0  0  1  0  0  1  0  0  0  1
901  0  0  0  0  0  0  0  1  0  1 ...  0  0  1  0  0  0  0  0  0  1
902  0  0  1  0  0  0  0  1  0  0 ...  0  0  0  0  0  0  0  0  0  1
903  1  0  1  0  0  0  0  0  0  0 ...  0  0  1  0  0  1  0  0  0  1
904  0  0  1  0  0  0  0  0  0  0 ...  0  0  1  0  0  1  0  0  0  1
905  0  0  0  0  0  0  0  0  0  0 ...  1  0  1  0  0  0  0  0  0  1
906  0  0  1  0  0  0  0  1  0  0 ...  0  0  1  0  0  0  0  0  0  1
907  0  0  1  0  0  0  0  0  0  0 ...  0  0  1  0  0  1  0  0  0  1
908  0  0  0  0  0  0  0  1  0  1 ...  0  0  1  0  0  0  0  0  0  1
909  0  0  0  0  0  0  0  0  1  1 ...  1  1  1  1  0  0  0  0  0  1
910  0  0  1  0  0  0  0  0  0  0 ...  0  0  1  0  0  1  0  0  0  1
911  0  0  0  0  0  0  0  0  1  1 ...  1  1  1  1  0  0  0  0  0  1
912  0  0  0  0  0  0  0  0  1  1 ...  1  1  1  1  0  0  0  0  0  1
913  0  0  0  0  0  0  0  0  1  1 ...  1  1  1  1  0  0  0  0  0  1
914  0  0  0  0  0  0  0  0  1  1 ...  1  1  1  1  0  0  0  0  0  1
915  1  0  1  0  0  0  0  0  0  0 ...  0  0  1  0  0  1  0  0  0  1
916  0  0  1  0  0  0  0  0  0  0 ...  0  0  1  0  0  1  0  0  0  1
917  1  0  0  0  0  0  0  1  0  0 ...  0  0  1  0  0  0  0  0  0  1
918  1  0  0  0  0  0  0  1  0  0 ...  0  0  1  0  0  0  0  0  0  1
919  0  0  1  0  0  0  0  0  0  0 ...  0  0  1  0  0  1  0  0  0  1
920  1  0  0  0  0  0  0  1  0  0 ...  0  0  1  0  0  0  0  0  0  1
921  1  0  0  0  0  0  0  1  0  0 ...  0  0  1  0  0  0  0  0  0  1
922  0  0  1  1  0  0  0  0  0  0 ...  0  0  1  0  0  1  0  0  0  1
923  0  0  1  1  0  0  0  0  0  0 ...  0  0  1  0  0  1  0  0  0  1
924  1  0  0  0  0  0  0  1  0  0 ...  0  0  1  0  0  0  0  0  0  1
925  0  0  0  0  1  0  0  0  0  0 ...  0  0  0  1  1  1  0  1  0  1
926  0  0  0  0  1  0  0  0  0  0 ...  0  0  0  1  1  1  0  

In [66]:
dfb = pd.DataFrame({'a' : ['one', 'one', 'two', 'three', 'two', 'one', 'six'],'c' : np.arange(7)})
dfb.values

array([['one', 0],
       ['one', 1],
       ['two', 2],
       ['three', 3],
       ['two', 4],
       ['one', 5],
       ['six', 6]], dtype=object)

In [88]:
k = np.random.permutation(7)
k[:7]
dfb.take(k[:4])

a  c
4  two  4
2  two  2
5  one  5
1  one  1

In [55]:
arr = DataFrame(np.arange(9).reshape((3, 3)))
np.random.shuffle(arr.values)
arr

0  1  2
0  6  7  8
1  0  1  2
2  3  4  5

In [37]:
dfb['c'][dfb.a.str.startswith('o')] = 42

F:\ProgramData\Anaconda3\envs\normal\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [21]:
dfb[dfb.a.str.startswith('o')]['c'] = 42

c:\python36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [1]:
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://longfengpili:mysql@123456@127.0.0.1:3306/chapter12?charset=utf8')
data = pd.read_sql('hunyinformodel1', engine)# 数据不是很大，不用分块了
data = data[['realIP','fullURL_1st']]
data.head()

F:\ProgramData\Anaconda3\envs\normal\lib\site-packages\pymysql\cursors.py:166: Warning: (1366, "Incorrect string value: '\\xD6\\xD0\\xB9\\xFA\\xB1\\xEA...' for column 'VARIABLE_VALUE' at row 481")
  result = self._query(query)
F:\ProgramData\Anaconda3\envs\normal\lib\site-packages\pymysql\cursors.py:166: Warning: (1287, "'@@tx_isolation' is deprecated and will be removed in a future release. Please use '@@transaction_isolation' instead")
  result = self._query(query)


realIP                                        fullURL_1st
0  2683657840  http://www.lawtime.cn/info/hunyin/hunyinfagui/...
1  1275347569  http://www.lawtime.cn/info/hunyin/lhlawlhxy/20...
2  1531496412  http://www.lawtime.cn/info/hunyin/hunyinfagui/...
3   838215995  http://www.lawtime.cn/info/hunyin/lhlawlhxy/20...
4   923358328  http://www.lawtime.cn/info/hunyin/zhonghun/zho...

In [2]:
data.realIP.values

array([2683657840, 1275347569, 1531496412, ..., 2526756791, 4267065457,
       3271035001], dtype=int64)

In [5]:
%time
index = data.realIP.value_counts().index
columns = data['fullURL_1st'].value_counts().index
result = DataFrame([],index=index,columns=columns)
for i in range(len(data)):
    x = data.loc[i]
    a = x.realIP
    b = x.fullURL_1st
    result.loc[a,b] = 1

Wall time: 0 ns


In [63]:
result[:10]

http://www.lawtime.cn/info/hunyin/lhlawlhxy/20110707137693.html  \
2609113527                                                  1                
3812410744                                                  1                
225896631                                                   1                
242673847                                                   1                
1190924814                                                  1                
276228279                                                   1                
259451063                                                   1                
2062227060                                                NaN                
2666105043                                                  1                
634787034                                                 NaN                

           http://www.lawtime.cn/info/hunyin/hunyinfagui/201411053308986.html  \
2609113527                                                  1                   
3812410744                                                NaN                   
225896631                                                   1                   
242673847                                                 NaN                   
1190924814                                                  1                   
276228279                                                 NaN                   
259451063                                                   1                   
2062227060                                                NaN                   
2666105043                                                  1                   
634787034                                                 NaN                   

           http://www.lawtime.cn/info/hunyin/jihuashengyu/20120215163891.html  \
2609113527                                                  1                   
3812410744                                                  1                   
225896631                                                 NaN                   
242673847                                                   1                   
1190924814                                                  1                   
276228279                                                 NaN                   
259451063                                                 NaN                   
2062227060                                                NaN                   
2666105043                                                NaN                   
634787034                                                 NaN                   

           http://www.lawtime.cn/info/hunyin/  \
2609113527                                  1   
3812410744                                  1   
225896631                                   1   
242673847                                   1   
1190924814                                  1   
276228279                                   1   
259451063                                   1   
2062227060                                NaN   
2666105043                                  1   
634787034                                 NaN   

           http://www.lawtime.cn/info/hunyin/jihuashengyu/201411053308990.html  \
2609113527                                                NaN                    
3812410744                                                NaN                    
225896631                                                 NaN                    
242673847                                                 NaN                    
1190924814                                                NaN                    
276228279                                                 NaN                    
259451063                                                 NaN                    
2062227060                                                NaN                    
2666105043                                                NaN                    
63478703

In [7]:
'hello {0:>{1}} '.format('Kevin',50)

'hello                                              Kevin '

In [1]:
plt?

In [8]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
arr2 = np.linalg.inv(arr)
arr2

array([[  9.00719925e+14,  -4.50359963e+14,  -1.80143985e+15,
          1.35107989e+15],
       [ -2.40191980e+15,   2.70215978e+15,   1.80143985e+15,
         -2.10167983e+15],
       [  2.10167983e+15,  -4.05323966e+15,   1.80143985e+15,
          1.50119988e+14],
       [ -6.00479950e+14,   1.80143985e+15,  -1.80143985e+15,
          6.00479950e+14]])

In [11]:
np.dot(arr,arr2)

array([[ 1.5   , -1.    ,  0.5   , -0.1875],
       [ 0.    ,  0.    ,  0.5   ,  0.    ],
       [ 0.    ,  0.    , -0.5   ,  0.    ],
       [ 0.    ,  8.    , -2.5   ,  4.    ]])

NameError: name 'arr·arr2' is not defined

In [15]:
np.dot(arr,arr)

array([[ 56,  62,  68,  74],
       [152, 174, 196, 218],
       [248, 286, 324, 362],
       [344, 398, 452, 506]])

In [16]:
arr*arr

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [17]:
arr*arr2

array([[  0.00000000e+00,  -4.50359963e+14,  -3.60287970e+15,
          4.05323966e+15],
       [ -9.60767921e+15,   1.35107989e+16,   1.08086391e+16,
         -1.47117588e+16],
       [  1.68134386e+16,  -3.64791570e+16,   1.80143985e+16,
          1.65131986e+15],
       [ -7.20575940e+15,   2.34187181e+16,  -2.52201579e+16,
          9.00719925e+15]])

In [20]:
arr3 = np.array([[1,2],[-1,3]])
arr4 = np.linalg.inv(arr3)
arr3
arr4

array([[ 1,  2],
       [-1,  3]])

array([[ 0.6, -0.4],
       [ 0.2,  0.2]])

In [21]:
arr3*arr4

array([[ 0.6, -0.8],
       [-0.2,  0.6]])