In [1]:
filename = './原书代码数据/chapter9/demo/data/moment.csv'
f = open(filename,'r')
data = pd.read_csv(f,sep=',')
f.close()
data

类别  序号    R通道一阶矩    G通道一阶矩    B通道一阶矩    R通道二阶矩    G通道二阶矩    B通道二阶矩  \
0     1   1  0.582823  0.543774  0.252829  0.014192  0.016144  0.041075   
1     1  10  0.641660  0.570657  0.213728  0.015439  0.011178  0.013708   
2     1  11  0.603684  0.576719  0.282254  0.008659  0.007075  0.012204   
3     1  12  0.589706  0.593743  0.252242  0.007908  0.005941  0.010568   
4     1  13  0.591096  0.592093  0.253595  0.007448  0.006495  0.012152   
5     1  14  0.588680  0.569634  0.318905  0.007528  0.005046  0.008386   
6     1  15  0.588493  0.573200  0.288403  0.007306  0.005103  0.011682   
7     1  16  0.618123  0.539779  0.274867  0.008526  0.006198  0.014825   
8     1  17  0.618460  0.539302  0.273901  0.008856  0.005895  0.014474   
9     1  18  0.664159  0.576430  0.294082  0.010958  0.007767  0.019057   
10    1  19  0.700704  0.601434  0.293268  0.008398  0.007158  0.013221   
11    1   2  0.563773  0.534851  0.271672  0.009723  0.007856  0.011873   
12    1  20  0.621952  0.548452  0.266310  0.010082  0.005803  0.011889   
13    1  21  0.611729  0.528410  0.238519  0.009792  0.006804  0.014620   
14    1  22  0.624196  0.568280  0.322870  0.008117  0.004635  0.010955   
15    1  23  0.692683  0.664455  0.279794  0.008884  0.005683  0.011976   
16    1  24  0.567814  0.585407  0.251615  0.007805  0.006038  0.012721   
17    1  25  0.549883  0.583302  0.294743  0.007412  0.005287  0.012042   
18    1  26  0.562742  0.564716  0.288781  0.006998  0.005068  0.011984   
19    1  27  0.663540  0.623294  0.211756  0.007988  0.005835  0.013615   
20    1  28  0.668542  0.620220  0.221886  0.007265  0.006331  0.010688   
21    1  29  0.577056  0.539380  0.281208  0.020312  0.015022  0.012230   
22    1   3  0.630328  0.594269  0.298577  0.007731  0.005877  0.010148   
23    1  30  0.639464  0.595075  0.240151  0.011428  0.008781  0.015076   
24    1  31  0.557840  0.535227  0.265775  0.013240  0.008698  0.014258   
25    1  32  0.620828  0.592502  0.220175  0.014568  0.010935  0.010109   
26    1  33  0.613659  0.583042  0.224204  0.013924  0.010943  0.010807   
27    1  34  0.603469  0.607894  0.254027  0.010828  0.006684  0.010370   
28    1  35  0.603320  0.602264  0.238729  0.009968  0.006598  0.010841   
29    1  36  0.634280  0.557472  0.181760  0.007525  0.005898  0.010193   
..   ..  ..       ...       ...       ...       ...       ...       ...   
173   4   1  0.420351  0.436173  0.167221  0.011220  0.007195  0.010565   
174   4  10  0.460341  0.482263  0.245450  0.010135  0.006233  0.011394   
175   4  11  0.409614  0.385250  0.170010  0.013155  0.008797  0.012362   
176   4  12  0.438122  0.454164  0.178447  0.009359  0.006555  0.012235   
177   4  13  0.426609  0.459610  0.256180  0.021658  0.014387  0.017249   
178   4  14  0.450980  0.484617  0.227987  0.008550  0.005562  0.011394   
179   4  15  0.461240  0.467853  0.122714  0.009813  0.006831  0.011739   
180   4  16  0.436534  0.472230  0.191351  0.009944  0.006870  0.013880   
181   4  17  0.458774  0.487272  0.218496  0.009037  0.005748  0.011921   
182   4  18  0.435620  0.476110  0.236417  0.008916  0.006087  0.013545   
183   4  19  0.481706  0.477087  0.206007  0.008120  0.006270  0.011846   
184   4   2  0.398801  0.425560  0.191341  0.014424  0.010462  0.015470   
185   4  20  0.485885  0.485946  0.202392  0.007838  0.006476  0.012028   
186   4  21  0.487928  0.487435  0.197227  0.007939  0.006151  0.011355   
187   4  22  0.462669  0.472833  0.164354  0.007966  0.005992  0.010920   
188   4  23  0.452650  0.454231  0.169218  0.009538  0.006302  0.011739   
189   4  24  0.478439  0.486933  0.157014  0.007786  0.005819  0.014261   
190   4   3  0.402068  0.431443  0.177364  0.010554  0.007287  0.010748   
191   4   4  0.488967  0.473824  0.182957  0.008834  0.008764  0.010826   
192   4   5  0.437753  0.431216  0.189605  0.011444  0.009159  0.011491   
193   4   6  0.461860  0.462713  0.240098  0.008155  0.006365  0.011982   
194   4   7  0.479319  0.47843

In [2]:
data['类别'].value_counts().sort_index()
data_value = data.values
from numpy.random import shuffle
shuffle(data_value)
data_train = data_value[:int(len(data)*0.8),:]
data_test = data_value[int(len(data)*0.8):,:]
data_train
DataFrame(data_train)[0].value_counts()

1    51
2    44
3    78
4    24
5     6
Name: 类别, dtype: int64

array([[ 1.00000000e+00,  3.30000000e+01,  6.13658792e-01, ...,
         4.47768100e-03,  5.14058700e-03,  2.72830500e-03],
       [ 2.00000000e+00,  1.00000000e+00,  4.95168678e-01, ...,
         1.53665200e-02,  1.60097020e-02,  1.97482400e-02],
       [ 1.00000000e+00,  1.00000000e+01,  6.41659507e-01, ...,
         9.72713600e-03, -3.72381400e-03, -3.77944800e-03],
       ...,
       [ 1.00000000e+00,  9.00000000e+00,  6.09155196e-01, ...,
        -4.94446600e-03, -3.38174000e-03,  2.39038000e-03],
       [ 4.00000000e+00,  2.40000000e+01,  4.78439446e-01, ...,
         4.32209100e-03, -3.57612700e-03, -8.19930000e-03],
       [ 4.00000000e+00,  1.50000000e+01,  4.61240440e-01, ...,
        -1.23856500e-03,  5.01603000e-04,  6.81254900e-03]])

3.0    60
1.0    46
2.0    33
4.0    19
5.0     4
Name: 0, dtype: int64

# 构建支持向量机

In [3]:
#构造特征和标签
x_train = data_train[:,2:]*30 #放大特征
y_train = data_train[:,0].astype(int)

x_test = data_test[:,2:]*30 #放大特征
y_test = data_test[:,0].astype(int)

In [4]:
from sklearn import svm
model = svm.SVC()
model.fit(x_train,y_train)

#保存模型
import pickle
pickle.dump(model,open('./原书代码数据/chapter9/demo/tmp/svm_xu.model','wb'))
#可以通过下面的语句load模型
#model = pickle.load(open('./原书代码数据/chapter9/demo/tmp/svm_xu.model','rb'))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [5]:
model.predict(x_train)

array([1, 2, 1, 1, 2, 1, 2, 3, 3, 2, 1, 1, 4, 3, 3, 1, 2, 3, 4, 1, 1, 1,
       1, 2, 2, 3, 3, 3, 3, 2, 2, 1, 1, 3, 3, 3, 3, 3, 3, 4, 2, 3, 3, 2,
       4, 3, 2, 2, 3, 1, 1, 1, 4, 3, 2, 2, 3, 4, 1, 2, 1, 1, 4, 3, 3, 1,
       4, 3, 3, 3, 1, 4, 1, 1, 4, 3, 3, 4, 3, 3, 3, 4, 3, 4, 1, 2, 4, 2,
       3, 1, 1, 1, 3, 2, 2, 1, 1, 3, 3, 2, 3, 1, 2, 3, 3, 4, 3, 3, 3, 2,
       1, 1, 1, 3, 2, 2, 3, 3, 1, 2, 3, 3, 2, 3, 3, 1, 2, 3, 3, 4, 3, 1,
       3, 2, 2, 2, 3, 2, 1, 5, 1, 2, 1, 1, 1, 3, 3, 3, 3, 3, 3, 5, 4, 4,
       3, 1, 1, 2, 1, 1, 3, 4])

In [12]:
train_predict = pd.concat([DataFrame(data_train),DataFrame(model.predict(x_train))],axis=1)
train_predict.columns = list(data.columns) + ['predict']
train_predict.head()

类别    序号    R通道一阶矩    G通道一阶矩    B通道一阶矩    R通道二阶矩    G通道二阶矩    B通道二阶矩  \
0  1.0  33.0  0.613659  0.583042  0.224204  0.013924  0.010943  0.010807   
1  2.0   1.0  0.495169  0.539358  0.416124  0.011314  0.009811  0.014751   
2  1.0  10.0  0.641660  0.570657  0.213728  0.015439  0.011178  0.013708   
3  1.0  12.0  0.589706  0.593743  0.252242  0.007908  0.005941  0.010568   
4  2.0   9.0  0.611124  0.609353  0.404027  0.007267  0.005746  0.008214   

     R通道三阶矩    G通道三阶矩    B通道三阶矩  predict  
0  0.004478  0.005141  0.002728        1  
1  0.015367  0.016010  0.019748        2  
2  0.009727 -0.003724 -0.003779        1  
3  0.003303 -0.003417 -0.005273        1  
4 -0.004596 -0.002181 -0.002052        2

In [7]:
from sklearn import metrics
cm_train = metrics.confusion_matrix(y_train,model.predict(x_train)) #训练样本的混淆矩阵

In [8]:
cm_train

array([[45,  1,  0,  0,  0],
       [ 0, 33,  0,  0,  0],
       [ 0,  0, 60,  0,  0],
       [ 0,  0,  2, 17,  0],
       [ 0,  0,  0,  2,  2]], dtype=int64)

In [16]:
metrics.confusion_matrix(np.array([1,2,3,4,5,3,2]),np.array([1,2,3,4,5,3,3])) #list/array

array([[1, 0, 0, 0, 0],
       [0, 1, 1, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int64)